import { writeFile, mkdir } from 'fs/promises';
import { join, dirname } from 'path';
import { AIAssistant } from '../models/project.js';
import { ProfileSelection } from '../models/profile.js';

export interface GeneratedFile {
  path: string;
  content: string;
}

export class AssistantFileWriter {
  generateFiles(
    assistant: AIAssistant,
    assembledContent: string,
    selection: ProfileSelection,
    projectPath: string
  ): GeneratedFile[] {
    const files: GeneratedFile[] = [];

    switch (assistant) {
      case 'claude-code':
        files.push(...this.generateClaudeCodeFiles(assembledContent, selection));
        break;
      case 'copilot':
        files.push(...this.generateCopilotFiles(assembledContent, selection));
        break;
      case 'gemini':
        files.push(...this.generateGeminiFiles(assembledContent, selection));
        break;
      case 'antigravity':
        files.push(...this.generateAntigravityFiles(assembledContent, selection));
        break;
      case 'codex':
        files.push(...this.generateCodexFiles(assembledContent, selection));
        break;
    }

    return files.map(file => ({
      ...file,
      path: join(projectPath, file.path)
    }));
  }

  async writeFiles(files: GeneratedFile[]): Promise<void> {
    for (const file of files) {
      await mkdir(dirname(file.path), { recursive: true });
      await writeFile(file.path, file.content, 'utf-8');
    }
  }

  private generateClaudeCodeFiles(content: string, selection: ProfileSelection): GeneratedFile[] {
    const header = `# Development Instructions

**Language:** ${selection.language}
**Project Type:** ${selection.projectType}
**Architecture:** ${selection.architecture}
**Level:** ${selection.level}

---

`;

    const footer = `

---
*Generated by aicgen*
`;

    return [{ path: 'claude.md', content: header + content + footer }];
  }

  private generateCopilotFiles(content: string, selection: ProfileSelection): GeneratedFile[] {
    const header = `# GitHub Copilot Instructions

**Language:** ${selection.language}
**Type:** ${selection.projectType}

---

`;

    return [{ path: '.github/copilot-instructions.md', content: header + content }];
  }

  private generateGeminiFiles(content: string, selection: ProfileSelection): GeneratedFile[] {
    const header = `# Gemini Development Guide

**Language:** ${selection.language}
**Type:** ${selection.projectType}
**Architecture:** ${selection.architecture}

---

`;

    return [{ path: '.gemini/instructions.md', content: header + content }];
  }

  private generateAntigravityFiles(content: string, selection: ProfileSelection): GeneratedFile[] {
    const header = `# Agent Rules

**Language:** ${selection.language}
**Type:** ${selection.projectType}
**Architecture:** ${selection.architecture}

---

`;

    return [{ path: '.agent/rules/instructions.md', content: header + content }];
  }

  private generateCodexFiles(content: string, selection: ProfileSelection): GeneratedFile[] {
    const header = `# Development Guide

**Language:** ${selection.language}
**Type:** ${selection.projectType}

---

`;

    return [{ path: '.codex/instructions.md', content: header + content }];
  }
}
