import { readFile } from 'fs/promises';
import { join } from 'path';
import { AIAssistant } from '../models/project.js';

export interface GeneratedFile {
  path: string;
  content: string;
  type: 'main' | 'guideline' | 'config' | 'agent' | 'universal' | 'workflow';
}

export interface WorkflowCommand {
  name: string;
  description: string;
  content: string;
}

export class WorkflowInjector {
  private constructor(private readonly commands: WorkflowCommand[]) {}

  static fromContent(sdlcContent: string): WorkflowInjector {
    return new WorkflowInjector(WorkflowInjector.parse(sdlcContent));
  }

  static async create(dataDir?: string): Promise<WorkflowInjector> {
    const root = dataDir ?? process.cwd();
    const sdlcPath = join(root, 'data/workflows/sdlc.md');
    try {
      const content = await readFile(sdlcPath, 'utf-8');
      return WorkflowInjector.fromContent(content);
    } catch (err) {
      throw new Error(
        `WorkflowInjector: could not read "${sdlcPath}". ` +
        `Pass the aicgen package root as dataDir, or ensure process.cwd() is the package root. ` +
        `Original error: ${(err as Error).message}`
      );
    }
  }

  private static parse(content: string): WorkflowCommand[] {
    const commands: WorkflowCommand[] = [];
    const blocks = content.split(/\n(?=## \/)/);

    for (const block of blocks) {
      const lines = block.trim().split('\n');
      const heading = lines[0];
      if (!heading.startsWith('## /')) continue;

      const nameMatch = heading.match(/^## \/(\w+)/);
      if (!nameMatch) {
        console.warn(`[WorkflowInjector] Skipping unrecognised command heading: "${heading}"`);
        continue;
      }
      const name = nameMatch[1];

      const hasDescription = lines[1] !== undefined && !lines[1].startsWith('**') && !lines[1].startsWith('#') && lines[1].trim() !== '';
      const description = hasDescription ? lines[1].trim() : '';
      const body = lines
        .slice(hasDescription ? 2 : 1)
        .join('\n')
        .replace(/\n---\s*$/, '')
        .trim();

      commands.push({ name, description, content: body });
    }

    return commands;
  }

  getCommands(): WorkflowCommand[] {
    return this.commands;
  }

  generateWorkflowFiles(assistant: AIAssistant): GeneratedFile[] {
    switch (assistant) {
      case 'claude-code':
        return this.commands.map(cmd => ({
          path: `.claude/commands/${cmd.name}.md`,
          content: this.formatClaudeCommand(cmd),
          type: 'workflow' as const,
        }));

      case 'copilot':
        return [{
          path: '.github/instructions/workflows.instructions.md',
          content: this.formatCopilotInstructions(),
          type: 'workflow' as const,
        }];

      case 'antigravity':
        return this.commands.map(cmd => ({
          path: `.agent/workflows/${cmd.name}.md`,
          content: this.formatAntigravityWorkflow(cmd),
          type: 'workflow' as const,
        }));

      case 'gemini':
      case 'codex':
        return [];

      default:
        return [];
    }
  }

  buildWorkflowSummary(): string {
    const flow = this.commands.map(cmd => `\`/${cmd.name}\``).join(' → ');
    const bullets = this.commands
      .map(cmd => `- \`/${cmd.name}\` — ${cmd.description}`)
      .join('\n');

    return `## Workflows

Use these slash commands for structured SDLC delivery:

Flow: ${flow}

${bullets}

`;
  }

  buildWorkflowSection(): string {
    const commandDocs = this.commands
      .map(cmd => `### /${cmd.name}\n${cmd.description}\n\n${cmd.content}`)
      .join('\n\n---\n\n');

    return `## SDLC Workflows

The following slash commands guide you through a structured SDLC. Always start with \`/spec\` and follow the flow: \`/spec\` → \`/research\` → \`/plan\` → \`/build\` → \`/check\` → \`/ship\`.

All spec and plan artifacts are saved to the \`docs/\` directory (created automatically if it does not exist).

${commandDocs}`;
  }

  private formatClaudeCommand(cmd: WorkflowCommand): string {
    return `# /${cmd.name}\n\n${cmd.description}\n\n${cmd.content}\n`;
  }

  private formatCopilotInstructions(): string {
    const commandDocs = this.commands
      .map(cmd => `### /${cmd.name}\n${cmd.description}\n\n${cmd.content}`)
      .join('\n\n---\n\n');

    return `---\napplyTo: "**/*"\ndescription: "SDLC workflow slash commands"\n---\n\n# SDLC Workflows\n\nFollow this structured workflow for every feature. Start with \`/spec\` and proceed in order.\n\nFlow: \`/spec\` → \`/research\` → \`/plan\` → \`/build\` → \`/check\` → \`/ship\`\n\nAll spec and plan artifacts are saved to the \`docs/\` directory.\n\n${commandDocs}\n\n---\n*Generated by aicgen*\n`;
  }

  private formatAntigravityWorkflow(cmd: WorkflowCommand): string {
    return `---\ndescription: "${cmd.description}"\n---\n\n${cmd.content}\n`;
  }
}
