#!/usr/bin/env bun
/**
 * Embed all guideline data into a TypeScript file for bundling into binary.
 * Run: bun run scripts/embed-data.ts
 */

import { access, readFile, readdir, writeFile } from 'fs/promises';
import { join } from 'path';
import YAML from 'yaml';

interface GuidelineMapping {
  path: string;
  category?: string;
  languages?: string[];
  levels?: string[];
  architectures?: string[];
  datasources?: string[];
  tags?: string[];
}

interface EmbeddedData {
  mappings: Record<string, GuidelineMapping>;
  guidelines: Record<string, string>;
}

export function getDataDir(): string {
  return process.env.AICGEN_DATA_DIR || join(process.cwd(), 'data');
}

export async function validateDataDir(dataDir: string): Promise<void> {
  const requiredFiles = [
    'guideline-mappings.yml',
    'workflows/sdlc.md',
  ];

  const missing: string[] = [];
  for (const file of requiredFiles) {
    try {
      await access(join(dataDir, file));
    } catch {
      missing.push(file);
    }
  }

  if (missing.length > 0) {
    throw new Error(
      [
        `Missing aicgen data files in ${dataDir}: ${missing.join(', ')}`,
        'Set AICGEN_DATA_DIR=/path/to/aicgen-data or initialize the data submodule with:',
        '  git submodule update --init --recursive data',
      ].join('\n')
    );
  }
}

async function readGuidelinesRecursively(dir: string, basePath: string = ''): Promise<Record<string, string>> {
  const guidelines: Record<string, string> = {};
  const entries = (await readdir(dir, { withFileTypes: true }))
    .sort((a, b) => a.name.localeCompare(b.name));

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    const relativePath = basePath ? `${basePath}/${entry.name}` : entry.name;

    if (entry.isDirectory()) {
      const subGuidelines = await readGuidelinesRecursively(fullPath, relativePath);
      Object.assign(guidelines, subGuidelines);
    } else if (entry.name.endsWith('.md')) {
      const content = await readFile(fullPath, 'utf-8');
      guidelines[relativePath] = content;
    }
  }

  return guidelines;
}

export async function buildEmbeddedDataOutput(dataDir: string): Promise<{ output: string; mappingCount: number; guidelineCount: number }> {
  await validateDataDir(dataDir);
  const mappingsPath = join(dataDir, 'guideline-mappings.yml');

  // Read mappings
  const mappingsContent = await readFile(mappingsPath, 'utf-8');
  const mappings = YAML.parse(mappingsContent) as Record<string, GuidelineMapping>;

  // Read all guidelines from data directory
  const guidelines = await readGuidelinesRecursively(dataDir);

  // Remove the mappings file and top-level index from guidelines
  delete guidelines['guideline-mappings.yml'];
  delete guidelines['index.md'];

  // Read SDLC workflow content
  const sdlcPath = join(dataDir, 'workflows/sdlc.md');
  const sdlcContent = await readFile(sdlcPath, 'utf-8');

  const data: EmbeddedData = { mappings, guidelines };

  // Generate TypeScript file
  const output = `// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/embed-data.ts
// Contains all guideline mappings and content embedded for binary distribution

export interface GuidelineMapping {
  path: string;
  category?: string;
  languages?: string[];
  levels?: string[];
  architectures?: string[];
  datasources?: string[];
  tags?: string[];
}

export interface EmbeddedData {
  mappings: Record<string, GuidelineMapping>;
  guidelines: Record<string, string>;
}

export const EMBEDDED_DATA: EmbeddedData = ${JSON.stringify(data, null, 2)};

export const GUIDELINE_COUNT = ${Object.keys(guidelines).length};
export const MAPPING_COUNT = ${Object.keys(mappings).length};
export const EMBEDDED_SDLC_CONTENT = ${JSON.stringify(sdlcContent)};
`;

  return {
    output,
    mappingCount: Object.keys(mappings).length,
    guidelineCount: Object.keys(guidelines).length,
  };
}

async function embedData() {
  console.log('📦 Embedding guideline data into TypeScript...\n');

  const dataDir = getDataDir();
  const { output, mappingCount, guidelineCount } = await buildEmbeddedDataOutput(dataDir);

  console.log(`  Data source: ${dataDir}`);
  console.log(`  Loaded ${mappingCount} guideline mappings`);
  console.log(`  Loaded ${guidelineCount} markdown files`);
  console.log('  Loaded SDLC workflow content');

  const outputPath = join(process.cwd(), 'src', 'embedded-data.ts');
  await writeFile(outputPath, output, 'utf-8');

  const sizeKB = (output.length / 1024).toFixed(1);
  console.log(`\n✅ Generated src/embedded-data.ts (${sizeKB} KB)`);
  console.log(`   ${mappingCount} mappings, ${guidelineCount} guidelines embedded`);
}

if (import.meta.main) {
  embedData().catch(err => {
    console.error('❌ Failed to embed data:', err);
    process.exit(1);
  });
}
